"""
Streamlit UI panel for editing and saving a PhosCrosstalk ``config.toml``.

Exposes all meaningful config sections as grouped widgets.
Writes a valid TOML file when the user clicks *Save config.toml*.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Path safety helper (kept local to avoid circular imports)
# ---------------------------------------------------------------------------

_BLOCKED_PATH_PREFIXES = (
    "/etc/", "/bin/", "/sbin/", "/usr/bin/", "/usr/sbin/",
    "/proc/", "/sys/", "/dev/", "/boot/",
)


def _check_path_safety(path: Path, label: str = "path") -> None:
    """Raise ``ValueError`` if *path* resolves to a restricted system location."""
    resolved = str(path.resolve())
    for prefix in _BLOCKED_PATH_PREFIXES:
        if resolved.startswith(prefix):
            raise ValueError(
                f"{label} resolves to a restricted system path: {resolved}"
            )


# ---------------------------------------------------------------------------
# TOML read / write  (stdlib tomllib for read, manual write for save)
# ---------------------------------------------------------------------------


def load_toml_to_dict(path: str | Path) -> dict[str, Any]:
    """
    Load *path* as a TOML file and return a plain nested ``dict``.

    Falls back to the built-in defaults if the file is missing.
    """
    from phoscrosstalk.config import _DEFAULTS, _deep_merge

    path = Path(path)
    _check_path_safety(path, label="config path")
    if not path.exists():
        return _deep_merge({}, _DEFAULTS)

    try:
        try:
            import tomllib
        except ModuleNotFoundError:
            import tomli as tomllib  # type: ignore[no-redef]

        with open(path, "rb") as fh:
            toml_data = tomllib.load(fh)
        return _deep_merge(_DEFAULTS, toml_data)
    except Exception:
        return _deep_merge({}, _DEFAULTS)


def save_dict_to_toml(cfg: dict[str, Any], path: str | Path) -> None:
    """
    Serialise *cfg* (a nested dict) to a TOML file at *path*.

    Uses a simple manual serialiser so no extra dependencies are required
    (``tomli-w`` is not in the project's dependency list).  Comments from
    the original file are not preserved; the output is clean structured TOML.
    """
    path = Path(path)
    _check_path_safety(path, label="save path")
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# PhosCrosstalk configuration — generated by the dashboard\n",
        "# Edit here or use the Config Editor tab in the Streamlit app.\n",
        "\n",
    ]

    def _fmt_value(v: Any) -> str:
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, str):
            escaped = v.replace("\\", "\\\\").replace('"', '\\"')
            return f'"{escaped}"'
        if isinstance(v, list):
            items = ", ".join(_fmt_value(i) for i in v)
            return f"[{items}]"
        if v is None:
            return "false"  # TOML has no null; use false as safe default
        return str(v)

    for section, values in cfg.items():
        if not isinstance(values, dict):
            continue
        lines.append(f"[{section}]\n")
        for key, val in values.items():
            if isinstance(val, dict):
                # Nested table — use inline table syntax
                inner = ", ".join(f"{k} = {_fmt_value(v)}" for k, v in val.items())
                lines.append(f"{key} = {{{inner}}}\n")
            else:
                lines.append(f"{key} = {_fmt_value(val)}\n")
        lines.append("\n")

    with open(path, "w", encoding="utf-8") as fh:
        fh.writelines(lines)


# ---------------------------------------------------------------------------
# Main render function
# ---------------------------------------------------------------------------


def render_config_editor(
        cfg: dict[str, Any],
        default_output_dir: str = "results",
) -> dict[str, Any]:
    """
    Render the full config editor UI and return the updated config dict.

    The caller is responsible for calling :func:`save_dict_to_toml` when the
    user requests a save; this function only manages the form widgets and
    returns the current in-memory config state.

    Args:
        cfg:                 Current config as a nested dict.
        default_output_dir:  Fallback output directory shown in the widget.

    Returns:
        Updated config dict reflecting the widget state.
    """
    import streamlit as st
    import copy

    cfg = copy.deepcopy(cfg)

    # ------------------------------------------------------------------
    # Grouped tabs inside the config editor
    # ------------------------------------------------------------------
    tabs = st.tabs(
        ["📂 Data", "🧬 Model", "⚙️ Solver", "🎯 Optimizer", "📐 Bounds",
         "⚖️ Loss", "🕐 Time", "📊 Analysis", "🖥️ Runtime", "🔬 Advanced"]
    )

    # ── Data ────────────────────────────────────────────────────────────
    with tabs[0]:
        st.subheader("Input / output paths")
        paths = cfg.setdefault("paths", {})

        paths["data"] = st.text_input(
            "Phosphosite / protein data CSV",
            value=paths.get("data", ""),
            help="Required. CSV with phosphosite and protein time-series data.",
        )
        paths["ptm_intra"] = st.text_input(
            "PTM intra-protein database (.db)",
            value=paths.get("ptm_intra", ""),
            help="Required. SQLite database of intra-protein PTM relationships.",
        )
        paths["ptm_inter"] = st.text_input(
            "PTM inter-protein database (.db)",
            value=paths.get("ptm_inter", ""),
            help="Required. SQLite database of inter-protein PTM relationships.",
        )

        out = paths.get("output_dir", default_output_dir)
        paths["output_dir"] = st.text_input(
            "Output directory",
            value=out,
            help="Directory where pipeline results will be written.",
        )
        if os.path.isdir(paths["output_dir"]) and os.listdir(paths["output_dir"]):
            st.warning(
                f"⚠️ Output directory **{paths['output_dir']!r}** already exists and is "
                "non-empty. A new run will overwrite or add files there."
            )

        st.divider()
        st.subheader("Optional input paths")
        st.caption("Leave blank to disable.")

        paths["rna_data"] = st.text_input(
            "RNA / mRNA data CSV",
            value=paths.get("rna_data", ""),
            help="Enables RNA coupling. Leave empty to disable RNA dynamics.",
        )
        paths["tf_net"] = st.text_input(
            "TF network CSV",
            value=paths.get("tf_net", ""),
            help="TF-driven activation terms. Leave empty to disable.",
        )
        paths["kinase_tsv"] = st.text_input(
            "Kinase-site prior TSV",
            value=paths.get("kinase_tsv", ""),
            help="Provides kinase-site assignment priors. Preferred over kea_ks_table.",
        )
        paths["kea_ks_table"] = st.text_input(
            "KEA kinase-substrate table",
            value=paths.get("kea_ks_table", ""),
            help="Alternative kinase-site source. Used only if kinase_tsv is empty.",
        )
        paths["crosstalk_tsv"] = st.text_input(
            "Crosstalk TSV",
            value=paths.get("crosstalk_tsv", ""),
            help="Optional explicit crosstalk edges.",
        )
        paths["unified_graph_pkl"] = st.text_input(
            "Unified kinase graph pickle",
            value=paths.get("unified_graph_pkl", ""),
            help="Required only when lambda_net > 0 for Laplacian regularisation.",
        )
        cfg["paths"] = paths

    # ── Model ───────────────────────────────────────────────────────────
    with tabs[1]:
        st.subheader("Biological model options")
        model = cfg.setdefault("model", {})

        model["mechanism"] = st.selectbox(
            "Phosphorylation mechanism",
            ["dist", "seq", "rand"],
            index=["dist", "seq", "rand"].index(model.get("mechanism", "dist")),
            help=(
                "**dist** – distributive (default). "
                "**seq** – sequential. "
                "**rand** – random."
            ),
        )
        model["scale_mode"] = st.selectbox(
            "Data scale mode",
            ["none", "minmax", "log-minmax"],
            index=["none", "minmax", "log-minmax"].index(
                model.get("scale_mode", "none")
            ),
            help=(
                "**none** – use values as-is. "
                "**minmax** – scale each trajectory to [0,1]. "
                "**log-minmax** – log-transform then min-max."
            ),
        )
        model["weight_scheme"] = st.selectbox(
            "Weighting scheme",
            ["uniform", "inverse_variance", "time_weighted"],
            index=["uniform", "inverse_variance", "time_weighted"].index(
                model.get("weight_scheme", "uniform")
            ),
            help=(
                "**uniform** – equal weight for all observed points. "
                "**inverse_variance** – higher weight for lower-variance measurements. "
                "**time_weighted** – emphasize selected time regions."
            ),
        )
        model["length_scale"] = st.number_input(
            "Length scale (local PTM coupling)",
            min_value=1.0,
            max_value=500.0,
            value=float(model.get("length_scale", 50.0)),
            step=5.0,
            help="Controls spatial decay of local PTM coupling in matrix Cl. "
                 "Smaller = more position-restricted.",
        )
        model["include_tfs_as_proteins"] = st.checkbox(
            "Include TFs as proteins",
            value=bool(model.get("include_tfs_as_proteins", False)),
            help="When enabled, TF-related proteins may be added if the TF network supports it.",
        )

        receptors_raw = ", ".join(model.get("receptors", []))
        receptors_txt = st.text_input(
            "Receptors (comma-separated)",
            value=receptors_raw,
            help="Protein names treated as externally stimulated receptors.",
        )
        model["receptors"] = [r.strip() for r in receptors_txt.split(",") if r.strip()]

        rec_kin_raw = ", ".join(model.get("receptor_kinases", []))
        rec_kin_txt = st.text_input(
            "Receptor kinases (comma-separated)",
            value=rec_kin_raw,
            help="Kinase names treated as externally stimulated receptor kinases.",
        )
        model["receptor_kinases"] = [r.strip() for r in rec_kin_txt.split(",") if r.strip()]

        cfg["model"] = model

    # ── Solver ──────────────────────────────────────────────────────────
    with tabs[2]:
        st.subheader("Diffrax ODE solver configuration")

        with st.expander("📖 Compatibility guide", expanded=False):
            st.info(
                "**jac_mode = fwd** requires **ode_adjoint = forward** or **direct**.\n\n"
                "**jac_mode = bwd** requires **ode_adjoint = recursive** or **checkpoint**.\n\n"
                "Do NOT combine `jac_mode = fwd` with `ode_adjoint = recursive` — "
                "RecursiveCheckpointAdjoint does not support forward-mode AD."
            )

        solver = cfg.setdefault("solver", {})

        ode_solvers = ["tsit5", "dopri5", "dopri8", "bosh3", "kvaerno3", "kvaerno4", "kvaerno5"]
        cur_ode = solver.get("ode_solver", "tsit5")
        solver["ode_solver"] = st.selectbox(
            "ODE solver",
            ode_solvers,
            index=ode_solvers.index(cur_ode) if cur_ode in ode_solvers else 0,
            help=(
                "**tsit5** – best first test, non-stiff.  "
                "**kvaerno4** – recommended for stiff biological systems.  "
                "**dopri5/8** – high-order non-stiff validation."
            ),
        )
        if solver["ode_solver"] in ("tsit5", "dopri5", "dopri8", "bosh3"):
            st.caption("ℹ️ Explicit solver selected — suitable for non-stiff or mildly stiff ODEs.")
        else:
            st.caption("ℹ️ Implicit stiff solver selected — recommended for coupled RNA/protein/phosphosite systems.")

        adjoints = ["forward", "recursive", "checkpoint", "direct", "backsolve", "none"]
        cur_adj = solver.get("ode_adjoint", "forward")
        solver["ode_adjoint"] = st.selectbox(
            "ODE adjoint",
            adjoints,
            index=adjoints.index(cur_adj) if cur_adj in adjoints else 0,
            help=(
                "**forward** – required for jac_mode=fwd. Recommended default.  "
                "**recursive** – RecursiveCheckpointAdjoint; use with jac_mode=bwd.  "
                "**checkpoint** – alias for recursive in some factory paths.  "
                "**backsolve** – continuous adjoint; approximate gradients, not recommended."
            ),
        )
        if solver["ode_adjoint"] == "backsolve":
            st.warning(
                "⚠️ BacksolveAdjoint gives approximate gradients. "
                "Not recommended for main fitting."
            )

        solver["rtol"] = st.number_input(
            "ODE relative tolerance (rtol)",
            min_value=1e-12,
            max_value=1e-2,
            value=float(solver.get("rtol", 1e-6)),
            format="%.2e",
            step=1e-7,
            help="ODE adaptive step relative tolerance. Tighter = slower but more accurate.",
        )
        solver["atol"] = st.number_input(
            "ODE absolute tolerance (atol)",
            min_value=1e-14,
            max_value=1e-3,
            value=float(solver.get("atol", 1e-9)),
            format="%.2e",
            step=1e-10,
            help="ODE adaptive step absolute tolerance.",
        )
        if solver["rtol"] < 1e-9 or solver["atol"] < 1e-12:
            st.warning("⚠️ Very tight tolerances may slow the solver significantly.")

        solver["max_steps"] = st.number_input(
            "ODE max internal steps",
            min_value=1024,
            max_value=1_048_576,
            value=int(solver.get("max_steps", 16384)),
            step=4096,
            help="Maximum internal ODE solver steps. Increase for stiff long-time simulations.",
        )
        solver["dt0"] = st.number_input(
            "Initial step size (dt0)",
            min_value=1e-8,
            max_value=10.0,
            value=float(solver.get("dt0", 0.01)),
            format="%.4f",
            help="Initial ODE step size. For fast early dynamics, 0.01 is reasonable.",
        )
        solver["root_find_max_steps"] = st.number_input(
            "Root-find max steps (implicit solvers)",
            min_value=1,
            max_value=100,
            value=int(solver.get("root_find_max_steps", 10)),
            help="Used only by implicit solvers (Kvaerno3/4/5). Increase if implicit stages fail.",
        )
        cfg["solver"] = solver

    # ── Optimizer ───────────────────────────────────────────────────────
    with tabs[3]:
        st.subheader("Optimisation / parameter fitting")
        opt = cfg.setdefault("optimisation", {})

        backends = [
            "optimistix", "jaxopt_lbfgsb", "jaxopt_pgd", "scipy_jax",
        ]
        cur_back = opt.get("optimizer_backend", "optimistix")
        opt["optimizer_backend"] = st.selectbox(
            "Optimizer backend",
            backends,
            index=backends.index(cur_back) if cur_back in backends else 0,
            help=(
                "**optimistix** – recommended default (Levenberg-Marquardt / Gauss-Newton).  "
                "**jaxopt_lbfgsb** – L-BFGS-B via JAXopt; good for smooth objectives.  "
            ),
        )
        ls_solvers = ["lm", "gauss_newton", "dogleg", "indirect_lm"]
        cur_ls = opt.get("ls_solver", "lm")
        opt["ls_solver"] = st.selectbox(
            "Least-squares solver (optimistix)",
            ls_solvers,
            index=ls_solvers.index(cur_ls) if cur_ls in ls_solvers else 0,
            help=(
                "**lm** – Levenberg-Marquardt. Best default. "
                "**gauss_newton** – faster near solution, less stable far from it. "
                "**dogleg** – trust-region; useful if LM behaves poorly."
            ),
        )

        jac_modes = ["fwd", "bwd"]
        cur_jac = opt.get("jac_mode", "fwd")
        opt["jac_mode"] = st.selectbox(
            "Jacobian mode",
            jac_modes,
            index=jac_modes.index(cur_jac) if cur_jac in jac_modes else 0,
            help=(
                "**fwd** – forward-mode AD; best for large residual vector / small parameter count. "
                "Requires ode_adjoint = forward.  "
                "**bwd** – reverse-mode; use if forward-mode fails or is too expensive. "
                "Requires ode_adjoint = recursive or checkpoint."
            ),
        )

        adjoints_opt = ["implicit", "checkpoint", "recursive"]
        cur_oa = opt.get("optx_adjoint", "implicit")
        opt["optx_adjoint"] = st.selectbox(
            "Optimistix adjoint",
            adjoints_opt,
            index=adjoints_opt.index(cur_oa) if cur_oa in adjoints_opt else 0,
            help="Controls gradients through the Optimistix solve itself. **implicit** is recommended.",
        )

        opt["n_starts"] = st.number_input(
            "Number of multi-starts",
            min_value=1,
            max_value=200,
            value=int(opt.get("n_starts", 3)),
            help="Number of random starting points. More starts increase coverage but also runtime.",
        )
        if opt["n_starts"] > 20:
            st.warning(
                f"⚠️ n_starts = {opt['n_starts']} will scale runtime roughly linearly. "
                "Consider whether you need that many starts."
            )

        opt["max_steps"] = st.number_input(
            "Max optimisation steps",
            min_value=10,
            max_value=100_000,
            value=int(opt.get("max_steps", 500)),
            help="Optimistix iteration cap per local optimisation run (NOT ODE max_steps).",
        )
        opt["rtol"] = st.number_input(
            "Optimistix convergence rtol",
            min_value=1e-14,
            max_value=1e-2,
            value=float(opt.get("rtol", 1e-8)),
            format="%.2e",
            help="Optimistix convergence relative tolerance. Not an ODE tolerance.",
        )
        opt["atol"] = st.number_input(
            "Optimistix convergence atol",
            min_value=1e-14,
            max_value=1e-2,
            value=float(opt.get("atol", 1e-8)),
            format="%.2e",
            help="Optimistix convergence absolute tolerance.",
        )
        if opt["rtol"] < 1e-10 or opt["atol"] < 1e-10:
            st.warning("⚠️ Very tight convergence tolerances may make optimisation very slow.")

        opt["lambda_net"] = st.number_input(
            "Network regularisation weight (lambda_net)",
            min_value=0.0,
            max_value=10.0,
            value=float(opt.get("lambda_net", 0.0001)),
            format="%.6f",
            help="Weight for kinase-network Laplacian regularisation. Requires unified_graph_pkl. Set 0 to disable.",
        )
        opt["reg_lambda"] = st.number_input(
            "L2 regularisation weight (reg_lambda)",
            min_value=0.0,
            max_value=10.0,
            value=float(opt.get("reg_lambda", 0.0001)),
            format="%.6f",
            help="L2 regularisation on the parameter vector theta.",
        )
        opt["verbose"] = st.checkbox(
            "Verbose optimisation logging",
            value=bool(opt.get("verbose", False)),
            help="Enable Optimistix internal progress logging. Can be noisy.",
        )
        opt["log_every"] = st.number_input(
            "Log every N steps (optax backends)",
            min_value=1,
            max_value=1000,
            value=int(opt.get("log_every", 100)),
            help="Diagnostic logging frequency for optax-style backends.",
        )
        cfg["optimisation"] = opt

    # ── Bounds ──────────────────────────────────────────────────────────
    with tabs[4]:
        st.subheader("Parameter bounds")
        st.info(
            "All bounds are applied in **log-space** for positive rate parameters. "
            "**rna_max** and **abundance_max** are ODE hard-clip values, not parameter bounds."
        )
        bounds = cfg.setdefault("bounds", {})

        c1, c2 = st.columns(2)
        with c1:
            bounds["rate_min"] = st.number_input(
                "rate_min (log-space floor)",
                min_value=1e-10,
                max_value=1.0,
                value=float(bounds.get("rate_min", 1e-5)),
                format="%.2e",
                help=(
                    "Log-space floor for ALL positive rate parameters. "
                    "Must be > 0 (enforced by the widget minimum)."
                ),
            )
            bounds["rate_max"] = st.number_input(
                "rate_max (generic ceiling)",
                min_value=0.01,
                max_value=1000.0,
                value=float(bounds.get("rate_max", 10.0)),
                help="Generic ceiling for rate parameters without a dedicated bound.",
            )
            bounds["protein_degradation_max"] = st.number_input(
                "protein_degradation_max",
                min_value=0.001,
                max_value=100.0,
                value=float(bounds.get("protein_degradation_max", 0.5)),
                help="Upper bound for protein degradation rates (d_deg).",
            )
            bounds["k_deact_max"] = st.number_input(
                "k_deact_max",
                min_value=0.001,
                max_value=100.0,
                value=float(bounds.get("k_deact_max", 2.0)),
                help="Upper bound for k_deact (protein deactivation). Separate from rate_max.",
            )
            bounds["kinase_rate_max"] = st.number_input(
                "kinase_rate_max",
                min_value=0.001,
                max_value=100.0,
                value=float(bounds.get("kinase_rate_max", 3.0)),
                help="Upper bound for kK_act and kK_deact.",
            )

        with c2:
            bounds["phosphatase_rate_max"] = st.number_input(
                "phosphatase_rate_max",
                min_value=0.001,
                max_value=100.0,
                value=float(bounds.get("phosphatase_rate_max", 5.0)),
                help="Upper bound for k_off (dephosphorylation rates).",
            )
            bounds["beta_coupling_max"] = st.number_input(
                "beta_coupling_max",
                min_value=0.001,
                max_value=100.0,
                value=float(bounds.get("beta_coupling_max", 3.0)),
                help="Upper bound for beta_g and beta_l (crosstalk coupling scalars).",
            )
            bounds["alpha_min"] = st.number_input(
                "alpha_min",
                min_value=1e-6,
                max_value=1.0,
                value=float(bounds.get("alpha_min", 0.01)),
                format="%.4f",
                help="Lower bound for alpha. Prevents collapse near zero.",
            )
            bounds["gamma_abs_max"] = st.number_input(
                "gamma_abs_max (raw tanh input)",
                min_value=0.01,
                max_value=20.0,
                value=float(bounds.get("gamma_abs_max", 2.0)),
                help="Absolute bound for raw gamma parameters (tanh-encoded, NOT log-space).",
            )
            if bounds.get("rate_max", 10.0) > 50:
                st.warning("⚠️ Extremely wide bounds may slow convergence.")

        st.divider()
        st.caption("ODE clip values (not parameter bounds for the optimizer):")
        c3, c4 = st.columns(2)
        with c3:
            bounds["rna_max"] = st.number_input(
                "rna_max (R_rna hard clip in ODE)",
                min_value=0.1,
                max_value=1000.0,
                value=float(bounds.get("rna_max", 10.0)),
                help="Hard clip for R_rna inside make_rhs(). NOT a parameter bound.",
            )
        with c4:
            bounds["abundance_max"] = st.number_input(
                "abundance_max (A hard clip in ODE)",
                min_value=0.1,
                max_value=100.0,
                value=float(bounds.get("abundance_max", 5.0)),
                help="Hard clip for protein abundance A in make_rhs() / simulation. NOT a parameter bound.",
            )
        cfg["bounds"] = bounds

    # ── Loss weights ─────────────────────────────────────────────────────
    with tabs[5]:
        st.subheader("Residual block weights")
        st.info(
            "Weights are applied as sqrt(weight) factors on the residual vector. "
            "Start with all 1.0 and adjust only if one block dominates the fit."
        )
        lw = cfg.setdefault("loss_weights", {})
        c1, c2, c3, c4 = st.columns(4)
        lw["phospho"] = c1.number_input(
            "phospho", min_value=0.0, value=float(lw.get("phospho", 1.0)), step=0.1,
            help="Weight for phosphosite trajectories.",
        )
        lw["abundance"] = c2.number_input(
            "abundance", min_value=0.0, value=float(lw.get("abundance", 1.0)), step=0.1,
            help="Weight for protein abundance trajectories.",
        )
        lw["mrna"] = c3.number_input(
            "mrna", min_value=0.0, value=float(lw.get("mrna", 1.0)), step=0.1,
            help="Weight for RNA / R_rna trajectories.",
        )
        lw["reg"] = c4.number_input(
            "reg", min_value=0.0, value=float(lw.get("reg", 1.0)), step=0.1,
            help="Weight multiplier for the regularisation block.",
        )
        cfg["loss_weights"] = lw

    # ── Time ─────────────────────────────────────────────────────────────
    with tabs[6]:
        st.subheader("Time-point and interpolation options")
        time_cfg = cfg.setdefault("time", {})

        pts_raw = time_cfg.get("mrna_time_points", [4, 8, 15, 30, 60, 120, 240, 480, 960])
        pts_txt = st.text_input(
            "mRNA time points (comma-separated, minutes)",
            value=", ".join(str(v) for v in pts_raw),
            help="RNA sampling time points matched to model proteins.",
        )
        try:
            time_cfg["mrna_time_points"] = [int(x.strip()) for x in pts_txt.split(",") if x.strip()]
        except ValueError:
            st.warning("⚠️ Could not parse mRNA time points — keeping previous value.")
            time_cfg["mrna_time_points"] = pts_raw

        interp_opts = ["piecewise_constant", "linear"]
        cur_interp = time_cfg.get("interpolation", "piecewise_constant")
        time_cfg["interpolation"] = st.selectbox(
            "Data interpolation method",
            interp_opts,
            index=interp_opts.index(cur_interp) if cur_interp in interp_opts else 0,
            help=(
                "**piecewise_constant** – holds values between time points; recommended for sparse omics data.  "
                "**linear** – smoother but may introduce artificial dynamics."
            ),
        )
        cfg["time"] = time_cfg

    # ── Analysis ─────────────────────────────────────────────────────────
    with tabs[7]:
        st.subheader("Downstream analyses after fitting")
        analysis = cfg.setdefault("analysis", {})

        analysis["tune"] = st.checkbox(
            "Run hyperparameter tuning",
            value=bool(analysis.get("tune", False)),
            help="Hyperparameter scan before final fitting. Disable during initial debugging.",
        )
        analysis["run_steadystate"] = st.checkbox(
            "Run steady-state analysis",
            value=bool(analysis.get("run_steadystate", False)),
            help="Long-horizon simulation to study convergence/relaxation.",
        )
        analysis["run_knockouts"] = st.checkbox(
            "Run knockout analysis",
            value=bool(analysis.get("run_knockouts", False)),
            help="In-silico knockout screen.",
        )
        analysis["run_sensitivity"] = st.checkbox(
            "Run global sensitivity analysis",
            value=bool(analysis.get("run_sensitivity", False)),
            help="SALib-based global sensitivity analysis. Can be slow.",
        )

        st.caption("Tip: disable all analyses during initial solver debugging.")
        cfg["analysis"] = analysis

    # ── Runtime ──────────────────────────────────────────────────────────
    with tabs[8]:
        st.subheader("CPU / XLA threading")
        st.info(
            "These settings are applied **before JAX imports** and control CPU parallelism. "
            "Changes here take effect on the next pipeline run."
        )
        runtime = cfg.setdefault("runtime", {})

        cpu_raw = runtime.get("cpu_threads", "auto")
        cpu_mode = st.radio(
            "cpu_threads",
            ["auto", "manual"],
            index=0 if cpu_raw == "auto" else 1,
            horizontal=True,
            help="auto: detect from SLURM/affinity/os.cpu_count(). manual: explicit integer.",
        )
        if cpu_mode == "manual":
            cpu_val = st.number_input(
                "CPU threads (integer)", min_value=1, max_value=512,
                value=int(cpu_raw) if str(cpu_raw).isdigit() else 4,
            )
            runtime["cpu_threads"] = cpu_val
        else:
            runtime["cpu_threads"] = "auto"

        parallel_raw = runtime.get("parallel_starts", "auto")
        par_mode = st.radio(
            "parallel_starts",
            ["auto", "manual"],
            index=0 if parallel_raw == "auto" else 1,
            horizontal=True,
            help="Number of starts to run concurrently.",
        )
        if par_mode == "manual":
            runtime["parallel_starts"] = st.number_input(
                "Parallel starts", min_value=1, max_value=256,
                value=int(parallel_raw) if str(parallel_raw).isdigit() else 2,
            )
        else:
            runtime["parallel_starts"] = "auto"

        runtime["use_physical_cores"] = st.checkbox(
            "Use physical cores (not logical CPUs)",
            value=bool(runtime.get("use_physical_cores", True)),
            help="When True, physical cores are used as budget. Ignored when SLURM_CPUS_PER_TASK is set.",
        )
        runtime["reserve_cores"] = st.number_input(
            "Reserve cores for OS",
            min_value=0,
            max_value=64,
            value=int(runtime.get("reserve_cores", 0)),
            help="CPUs to reserve for the OS / parent process.",
        )
        cfg["runtime"] = runtime

    # ── Advanced ─────────────────────────────────────────────────────────
    with tabs[9]:
        st.subheader("Simulation, Neural ODE, and Debug")

        with st.expander("Dense output (post-fit simulation)", expanded=True):
            sim = cfg.setdefault("simulation", {})
            sim["dense_output"] = st.checkbox(
                "Run dense simulation after fitting",
                value=bool(sim.get("dense_output", True)),
            )
            sim["save_dense"] = st.checkbox(
                "Save dense timeseries TSV",
                value=bool(sim.get("save_dense", True)),
            )
            sim["dense_n_points"] = st.number_input(
                "Dense grid points",
                min_value=10, max_value=10000,
                value=int(sim.get("dense_n_points", 200)),
            )
            cfg["simulation"] = sim

        with st.expander("Neural ODE (latent-rate refinement)", expanded=False):
            neural = cfg.setdefault("neural_ode", {})
            neural["enabled"] = st.checkbox(
                "Enable neural latent-rate refinement",
                value=bool(neural.get("enabled", False)),
                help="Runs a post-fit MLP to refine latent rates. Disabled by default.",
            )
            if neural["enabled"]:
                col1, col2 = st.columns(2)
                neural["width"] = col1.number_input(
                    "MLP hidden width", min_value=4, max_value=512,
                    value=int(neural.get("width", 32)),
                )
                neural["depth"] = col2.number_input(
                    "MLP depth", min_value=1, max_value=10,
                    value=int(neural.get("depth", 2)),
                )
                neural["steps"] = st.number_input(
                    "Training steps", min_value=10, max_value=100_000,
                    value=int(neural.get("steps", 500)),
                )
                neural["learning_rate"] = st.number_input(
                    "Learning rate", min_value=1e-6, max_value=1.0,
                    value=float(neural.get("learning_rate", 1e-3)),
                    format="%.2e",
                )
                neural["seed"] = st.number_input(
                    "Random seed", min_value=0, max_value=2 ** 31,
                    value=int(neural.get("seed", 0)),
                )
            cfg["neural_ode"] = neural

        with st.expander("Derived rates", expanded=False):
            dr = cfg.setdefault("derived_rates", {})
            dr["s_prod_fn"] = st.selectbox(
                "s_prod function",
                ["softplus", "linear"],
                index=["softplus", "linear"].index(dr.get("s_prod_fn", "softplus")),
                help="**softplus** – positive smooth production (recommended). **linear** – signed.",
            )
            dr["rna_relax"] = st.number_input(
                "RNA relaxation (rna_relax)",
                min_value=0.001, max_value=10.0,
                value=float(dr.get("rna_relax", 0.1)),
                format="%.3f",
                help="Higher = faster RNA tracking but potentially stiffer ODEs.",
            )
            cfg["derived_rates"] = dr

        with st.expander("Debug flags", expanded=False):
            dbg = cfg.setdefault("debug", {})
            dbg["save_jaxpr_reports"] = st.checkbox(
                "Save JAXpr reports (developer)",
                value=bool(dbg.get("save_jaxpr_reports", False)),
                help="Capture JAX computation graphs and save HTML/PDF reports. Requires WeasyPrint.",
            )
            cfg["debug"] = dbg

    return cfg
