"""
Optimizer-based uncertainty analysis for PhosCrosstalk model parameters.

This module provides uncertainty estimates for fitted mechanistic ODE parameters
after the main optimisation step has produced a best-fit parameter vector
(`theta_best`). The preferred uncertainty methods are optimizer-based rather
than MCMC-based, because PhosCrosstalk uses bounded, transformed parameters,
Diffrax ODE solves, multiple objective components, and residual-vector
least-squares optimisation.

Primary methods
---------------
1. Residual bootstrap

   The fitted model is simulated at `theta_best`, residuals are computed against
   the observed data, synthetic datasets are generated by resampling those
   residuals, and the model is refitted to each synthetic dataset using the same
   optimisation backend as the original fit.

   This produces an empirical distribution of refitted parameter vectors.

2. Profile likelihood

   Selected parameters are fixed over a grid of values between their bounds.
   For each fixed value, the remaining model parameters are re-optimised. The
   resulting profiled total loss is used to assess practical identifiability.

   Interpretation:
       flat profile       -> weakly identifiable / non-identifiable parameter
       sharp profile      -> well-constrained parameter
       boundary minimum   -> bound-constrained or poorly determined parameter

Expected main.py usage
----------------------
    from phoscrosstalk.posterior import run_optimizer_uncertainty

    run_optimizer_uncertainty(
        outdir=outdir,
        problem=problem,
        theta_best=theta_best,
        posterior_cfg=cfg.posterior,
        theta_names=theta_names,
        w_phospho=args.loss_weight_phospho,
        w_abundance=args.loss_weight_abundance,
        w_reg=args.loss_weight_reg,
        w_mrna=args.loss_weight_mrna,
    )

Configuration
-------------
The uncertainty methods are controlled through the existing [posterior] section
of config.toml for backward compatibility.

Typical configuration:

    [posterior]
    enabled = true
    method = "both"  # "bootstrap", "profile", or "both"

    n_bootstrap = 100
    bootstrap_residual_mode = "case"
    bootstrap_max_steps = 200
    bootstrap_start_jitter = 0.0
    rebuild_s_prod_from_bootstrap = true
    save_prediction_intervals = true

    profile_params = 12
    profile_points = 21
    profile_grid_fraction = 1.0
    profile_fix_lambda = 1e8
    profile_max_steps = 300

Outputs
-------
Written to {outdir}/uncertainty/.

Residual bootstrap outputs:

    bootstrap_samples.npz
    bootstrap_summary.tsv
    bootstrap_failures.tsv
    bootstrap_metadata.json
    bootstrap_parameter_distributions.png
    bootstrap_prediction_intervals/

Profile-likelihood outputs:

    profile_likelihood/profile_likelihood.tsv
    profile_likelihood/profile_thetas.npz
    profile_likelihood/profile_metadata.json
    profile_likelihood/profile_param_*.png

Summary columns
---------------
Bootstrap summaries contain:

    parameter
    mean
    std
    median
    q2.5
    q25
    q75
    q97.5
    min
    max
    n_success

Design notes
------------
All refits reuse the existing optimisation machinery rather than introducing a
new statistical backend. This keeps uncertainty estimation consistent with the
actual fitted objective, including phosphosite, abundance, mRNA, regularisation,
loss weights, bounds, solver settings, and backend-specific optimisation logic.
"""

from __future__ import annotations

import json
import os
from typing import Any

import numpy as np
import multiprocessing as mp
import pickle
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from types import SimpleNamespace

from phoscrosstalk.logger import get_logger

logger = get_logger()

# ---------------------------------------------------------------------------
# Optimizer-based uncertainty: residual bootstrap + profile likelihood
# ---------------------------------------------------------------------------

def _can_pickle(obj) -> bool:
    try:
        pickle.dumps(obj)
        return True
    except Exception:
        return False


def _find_non_picklable_items(mapping: dict) -> list[str]:
    bad = []
    for key, value in mapping.items():
        try:
            pickle.dumps(value)
        except Exception:
            bad.append(key)
    return bad


def _make_runtime_args_from_problem(problem, posterior_cfg, *, n_tasks: int):
    """
    Build a small args namespace for runtime_env.plan_cpu_runtime().

    Uses runtime settings stored on problem when main.py attaches them.
    Falls back to posterior_cfg or safe defaults.
    """
    return SimpleNamespace(
        cpu_threads=getattr(
            problem,
            "cpu_threads",
            _cfg_get(posterior_cfg, "cpu_threads", "auto"),
        ),
        parallel_starts=getattr(
            problem,
            "parallel_starts",
            _cfg_get(posterior_cfg, "parallel_refits", "auto"),
        ),
        threads_per_start=getattr(
            problem,
            "threads_per_start",
            _cfg_get(posterior_cfg, "threads_per_refit", "auto"),
        ),
        use_physical_cores=getattr(
            problem,
            "use_physical_cores",
            _cfg_get(posterior_cfg, "use_physical_cores", True),
        ),
        reserve_cores=getattr(
            problem,
            "reserve_cores",
            _cfg_get(posterior_cfg, "reserve_cores", 0),
        ),
        n_starts=int(n_tasks),
    )


def _plan_uncertainty_runtime(problem, posterior_cfg, *, n_tasks: int, label: str):
    from phoscrosstalk.runtime_env import plan_cpu_runtime  # noqa: PLC0415

    args = _make_runtime_args_from_problem(
        problem,
        posterior_cfg,
        n_tasks=n_tasks,
    )

    plan = plan_cpu_runtime(
        cpu_threads=args.cpu_threads,
        n_starts=args.n_starts,
        parallel_starts=args.parallel_starts,
        threads_per_start=args.threads_per_start,
        reserve_cores=args.reserve_cores,
        use_physical_cores=args.use_physical_cores,
    )

    topo = plan.topo

    logger.info(
        "[%s/runtime] CPU plan:"
        "\n    SLURM active         = %s"
        "\n    logical CPUs         = %s"
        "\n    physical cores       = %s"
        "\n    affinity CPUs        = %s"
        "\n    usable CPUs          = %s"
        "\n    CPU source           = %s"
        "\n    tasks                = %s"
        "\n    parallel workers     = %s"
        "\n    threads per worker   = %s"
        "\n    XLA intra-op threads = %s"
        "\n    BLAS/OpenMP threads  = %s",
        label,
        topo.slurm_cpus is not None,
        topo.logical_cpus,
        topo.physical_cores if topo.physical_cores is not None else "unknown",
        topo.affinity_cpus if topo.affinity_cpus is not None else "n/a",
        plan.total_available_cpus,
        topo.source,
        n_tasks,
        plan.n_parallel_runs,
        plan.threads_per_run,
        plan.xla_threads,
        plan.blas_threads,
    )

    return plan

def _base_refit_kwargs_from_problem(
        *,
        problem,
        w_phospho: float,
        w_abundance: float,
        w_reg: float,
        w_mrna: float,
) -> dict:
    """
    Build picklable kwargs for make_residuals_fn().

    Workers receive this dict, replace P_data/A_scaled/RNA as needed,
    rebuild k_act_fn/s_prod_fn locally, and then call make_residuals_fn().
    """
    kwargs = {
        "dims": problem.dims,
        "t": np.asarray(problem.t, dtype=np.float64),
        "P_data": np.asarray(problem.P_data, dtype=np.float64),
        "A_scaled": np.asarray(problem.A_scaled, dtype=np.float64),
        "prot_idx_for_A": np.asarray(problem.prot_idx_for_A, dtype=int),
        "W_data": np.asarray(problem.W_data, dtype=np.float64),
        "W_data_prot": np.asarray(problem.W_data_prot, dtype=np.float64),
        "Cg": np.asarray(problem.Cg, dtype=np.float64),
        "Cl": np.asarray(problem.Cl, dtype=np.float64),
        "site_prot_idx": np.asarray(problem.site_prot_idx, dtype=int),
        "K_site_kin": np.asarray(problem.K_site_kin, dtype=np.float64),
        "R": np.asarray(problem.R, dtype=np.float64),
        "L_alpha": np.asarray(problem.L_alpha, dtype=np.float64),
        "kin_to_prot_idx": np.asarray(problem.kin_to_prot_idx, dtype=int),
        "receptor_mask_prot": np.asarray(problem.receptor_mask_prot),
        "receptor_mask_kin": np.asarray(problem.receptor_mask_kin),
        "mechanism": str(problem.mechanism),
        "lambda_net": float(problem.lambda_net),
        "reg_lambda": float(problem.reg_lambda),
        "w_phospho": float(w_phospho),
        "w_abundance": float(w_abundance),
        "w_reg": float(w_reg),
        "w_mrna": float(w_mrna),
        "rtol": float(getattr(problem, "rtol", 1e-6)),
        "atol": float(getattr(problem, "atol", 1e-9)),
        "max_steps": int(getattr(problem, "max_steps", 16384)),
        "t_mrna": _as_optional_array(getattr(problem, "t_rna", None)),
        "rna_data_scaled": _as_optional_array(getattr(problem, "rna_obs_matched", None)),
        "rna_model_prot_idx": _as_optional_array(
            getattr(problem, "rna_model_prot_idx", None),
            dtype=int,
        ),
        "rna_obs_idx": _as_optional_array(
            getattr(problem, "rna_obs_idx", None),
            dtype=int,
        ),
        "rna_fit_genes": getattr(problem, "rna_fit_genes", None),
        "R_data0": _as_optional_array(getattr(problem, "R_data0", None)),
        "W_data_mrna": _as_optional_array(getattr(problem, "W_data_mrna", None)),
        "rna_relax": float(getattr(problem, "rna_relax", 0.1)),
        "ode_solver_kind": str(getattr(problem, "ode_solver_kind", "tsit5")),
        "ode_adjoint_kind": str(getattr(problem, "ode_adjoint_kind", "forward")),
        "dt0": float(getattr(problem, "ode_dt0", 0.01)),
        "root_find_max_steps": int(getattr(problem, "ode_root_find_max_steps", 10)),
        "xl": np.asarray(problem.xl, dtype=np.float64),
        "xu": np.asarray(problem.xu, dtype=np.float64),
        "loss_type": str(getattr(problem, "loss_type", "mse")),
        "pseudo_huber_delta": float(getattr(problem, "pseudo_huber_delta", 0.1)),
        "slope_lambda": float(getattr(problem, "slope_lambda", 0.1)),
    }

    k_rebuild = getattr(problem, "_k_act_rebuild_kwargs", None)
    s_rebuild = getattr(problem, "_s_prod_rebuild_kwargs", None)

    if k_rebuild is not None:
        kwargs["_k_act_rebuild_kwargs"] = dict(k_rebuild)
    else:
        kwargs["k_act_fn"] = getattr(problem, "k_act_fn", None)

    if s_rebuild is not None:
        kwargs["_s_prod_rebuild_kwargs"] = dict(s_rebuild)
    else:
        kwargs["s_prod_fn"] = getattr(problem, "s_prod_fn", None)

    return kwargs


def _residuals_fn_from_refit_kwargs(refit_kwargs: dict):
    from phoscrosstalk.derived_rates import make_k_act_fn, make_s_prod_fn  # noqa: PLC0415
    from phoscrosstalk.optimization import make_residuals_fn  # noqa: PLC0415

    kwargs = dict(refit_kwargs)

    if "_k_act_rebuild_kwargs" in kwargs:
        k_kwargs = kwargs.pop("_k_act_rebuild_kwargs")
        kwargs["k_act_fn"] = make_k_act_fn(**k_kwargs)

    if "_s_prod_rebuild_kwargs" in kwargs:
        s_kwargs = kwargs.pop("_s_prod_rebuild_kwargs")
        kwargs["s_prod_fn"] = make_s_prod_fn(**s_kwargs)

    return make_residuals_fn(**kwargs)

def _bootstrap_refit_worker(task):
    """
    Process worker for one bootstrap refit.

    Must be top-level so it is picklable. Applies CPU/XLA env before importing
    optimization/JAX-heavy code.
    """
    (
        b,
        theta0,
        refit_kwargs,
        P_boot,
        A_boot,
        R_boot,
        max_steps,
        rtol,
        atol,
        ls_solver,
        optx_adjoint,
        jac_mode,
        threads_per_worker,
        rebuild_s_prod_from_bootstrap,
    ) = task

    from phoscrosstalk import runtime_env  # noqa: PLC0415

    runtime_env.apply_cpu_env(int(threads_per_worker), overwrite=True)

    try:
        from phoscrosstalk.optimization import run_single_optimisation  # noqa: PLC0415

        kwargs = dict(refit_kwargs)
        kwargs["P_data"] = np.asarray(P_boot, dtype=np.float64)

        if A_boot is not None:
            kwargs["A_scaled"] = np.asarray(A_boot, dtype=np.float64)

        if R_boot is not None:
            kwargs["rna_data_scaled"] = np.asarray(R_boot, dtype=np.float64)

        if rebuild_s_prod_from_bootstrap and "_s_prod_rebuild_kwargs" in kwargs:
            s_kwargs = dict(kwargs["_s_prod_rebuild_kwargs"])
            if "Y_data" in s_kwargs:
                s_kwargs["Y_data"] = np.asarray(P_boot, dtype=np.float64)
            kwargs["_s_prod_rebuild_kwargs"] = s_kwargs

        residuals_fn = _residuals_fn_from_refit_kwargs(kwargs)

        theta_opt, total_loss, f1, f2, f3, f4 = run_single_optimisation(
            residuals_fn,
            np.asarray(theta0, dtype=np.float64),
            max_steps=int(max_steps),
            rtol=float(rtol),
            atol=float(atol),
            verbose=False,
            ls_solver=str(ls_solver),
            optx_adjoint=str(optx_adjoint),
            jac_mode=str(jac_mode),
        )

        return (
            int(b),
            True,
            np.asarray(theta_opt, dtype=np.float64),
            float(total_loss),
            float(f1),
            float(f2),
            float(f3),
            float(f4),
            "",
        )

    except Exception as exc:
        return (
            int(b),
            False,
            None,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            f"{type(exc).__name__}: {exc}",
        )

def _cfg_get(cfg, name: str, default):
    """Small helper that supports SimpleNamespace-like config objects."""
    if cfg is None:
        return default
    return getattr(cfg, name, default)


def _as_optional_array(x, *, dtype=np.float64):
    if x is None:
        return None
    arr = np.asarray(x, dtype=dtype)
    return arr


def _clip_theta_open(theta, xl, xu, rel_eps: float = 1e-10, abs_eps: float = 1e-12):
    """Clip theta into the open interval (xl, xu) for stable refit starts."""
    theta = np.asarray(theta, dtype=np.float64)
    xl = np.asarray(xl, dtype=np.float64)
    xu = np.asarray(xu, dtype=np.float64)
    span = xu - xl
    eps = np.maximum(rel_eps * span, abs_eps)
    return np.clip(theta, xl + eps, xu - eps)


def _rebuild_rate_functions_for_refit(problem, *, P_data_for_s_prod=None):
    """
    Rebuild k_act_fn and s_prod_fn from picklable kwargs when available.

    For bootstrap refits, s_prod_fn can optionally be rebuilt using the
    bootstrapped phosphosite data. This keeps the derived synthesis prior
    internally consistent with the synthetic dataset.
    """
    k_act_fn = getattr(problem, "k_act_fn", None)
    s_prod_fn = getattr(problem, "s_prod_fn", None)

    k_kwargs = getattr(problem, "_k_act_rebuild_kwargs", None)
    if k_kwargs is not None:
        from phoscrosstalk.derived_rates import make_k_act_fn  # noqa: PLC0415

        k_act_fn = make_k_act_fn(**dict(k_kwargs))

    s_kwargs = getattr(problem, "_s_prod_rebuild_kwargs", None)
    if s_kwargs is not None:
        from phoscrosstalk.derived_rates import make_s_prod_fn  # noqa: PLC0415

        s_kwargs = dict(s_kwargs)
        if P_data_for_s_prod is not None and "Y_data" in s_kwargs:
            s_kwargs["Y_data"] = np.asarray(P_data_for_s_prod, dtype=np.float64)
        s_prod_fn = make_s_prod_fn(**s_kwargs)

    return k_act_fn, s_prod_fn


def _make_refit_residuals_fn(
        *,
        problem,
        P_data,
        A_scaled=None,
        rna_data_scaled=None,
        w_phospho=1.0,
        w_abundance=1.0,
        w_reg=1.0,
        w_mrna=1.0,
        rebuild_s_prod_from_P=True,
):
    """Build a make_residuals_fn callable for a synthetic/refit dataset."""
    from phoscrosstalk.optimization import make_residuals_fn  # noqa: PLC0415

    P_data = np.asarray(P_data, dtype=np.float64)

    if A_scaled is None:
        A_scaled = getattr(problem, "A_scaled", None)
    if rna_data_scaled is None:
        rna_data_scaled = getattr(problem, "rna_obs_matched", None)

    k_act_fn, s_prod_fn = _rebuild_rate_functions_for_refit(
        problem,
        P_data_for_s_prod=P_data if rebuild_s_prod_from_P else None,
    )

    return make_residuals_fn(
        dims=problem.dims,
        t=problem.t,
        P_data=P_data,
        A_scaled=np.asarray(A_scaled, dtype=np.float64),
        prot_idx_for_A=problem.prot_idx_for_A,
        W_data=problem.W_data,
        W_data_prot=problem.W_data_prot,
        Cg=problem.Cg,
        Cl=problem.Cl,
        site_prot_idx=problem.site_prot_idx,
        K_site_kin=problem.K_site_kin,
        R=problem.R,
        L_alpha=problem.L_alpha,
        kin_to_prot_idx=problem.kin_to_prot_idx,
        receptor_mask_prot=problem.receptor_mask_prot,
        receptor_mask_kin=problem.receptor_mask_kin,
        mechanism=problem.mechanism,
        lambda_net=problem.lambda_net,
        reg_lambda=problem.reg_lambda,
        w_phospho=w_phospho,
        w_abundance=w_abundance,
        w_reg=w_reg,
        w_mrna=w_mrna,
        rtol=getattr(problem, "rtol", 1e-6),
        atol=getattr(problem, "atol", 1e-9),
        max_steps=getattr(problem, "max_steps", 16384),
        k_act_fn=k_act_fn,
        s_prod_fn=s_prod_fn,
        t_mrna=getattr(problem, "t_rna", None),
        rna_data_scaled=rna_data_scaled,
        rna_model_prot_idx=getattr(problem, "rna_model_prot_idx", None),
        rna_obs_idx=getattr(problem, "rna_obs_idx", None),
        rna_fit_genes=getattr(problem, "rna_fit_genes", None),
        R_data0=getattr(problem, "R_data0", None),
        W_data_mrna=getattr(problem, "W_data_mrna", None),
        rna_relax=getattr(problem, "rna_relax", 0.1),
        ode_solver_kind=getattr(problem, "ode_solver_kind", "tsit5"),
        ode_adjoint_kind=getattr(problem, "ode_adjoint_kind", "forward"),
        dt0=getattr(problem, "ode_dt0", 0.01),
        root_find_max_steps=getattr(problem, "ode_root_find_max_steps", 10),
        xl=getattr(problem, "xl", None),
        xu=getattr(problem, "xu", None),
        loss_type=getattr(problem, "loss_type", "mse"),
        pseudo_huber_delta=getattr(problem, "pseudo_huber_delta", 0.1),
        slope_lambda=getattr(problem, "slope_lambda", 0.1),
    )


def _simulate_full_for_uncertainty(problem, theta):
    """Return full simulation dict, with a fallback for older problem objects."""
    theta = np.asarray(theta, dtype=np.float64)
    if hasattr(problem, "simulate_full"):
        out = problem.simulate_full(theta)
        if isinstance(out, dict):
            return out

    P_sim = np.asarray(problem.simulate(theta), dtype=np.float64)
    return {
        "P_sim": P_sim,
        "A_sim": None,
        "R_sim_rna": None,
        "R_sim": None,
    }


def _resample_residual_matrix(rng, resid, mode: str = "case"):
    """
    Resample a residual matrix with shape (entities, time).

    mode='case' resamples complete entity-level residual trajectories.
    mode='element' resamples individual finite residual values.
    mode='time' resamples time columns.
    """
    resid = np.asarray(resid, dtype=np.float64)

    if resid.size == 0:
        return resid.copy()

    if mode == "case" and resid.ndim == 2 and resid.shape[0] > 0:
        idx = rng.integers(0, resid.shape[0], size=resid.shape[0])
        return resid[idx, :]

    if mode == "time" and resid.ndim == 2 and resid.shape[1] > 0:
        idx = rng.integers(0, resid.shape[1], size=resid.shape[1])
        return resid[:, idx]

    finite = resid[np.isfinite(resid)]
    if finite.size == 0:
        return np.zeros_like(resid)
    sampled = rng.choice(finite, size=resid.shape, replace=True)
    return np.asarray(sampled, dtype=np.float64)


def _summarize_samples(samples, theta_names):
    import pandas as pd  # noqa: PLC0415

    samples = np.asarray(samples, dtype=np.float64)
    rows = []
    for i, name in enumerate(theta_names):
        col = samples[:, i]
        finite = col[np.isfinite(col)]
        if finite.size == 0:
            rows.append({
                "parameter": name,
                "mean": np.nan,
                "std": np.nan,
                "median": np.nan,
                "q2.5": np.nan,
                "q25": np.nan,
                "q75": np.nan,
                "q97.5": np.nan,
                "min": np.nan,
                "max": np.nan,
                "n_success": 0,
            })
            continue
        rows.append({
            "parameter": name,
            "mean": float(np.mean(finite)),
            "std": float(np.std(finite, ddof=1)) if finite.size > 1 else 0.0,
            "median": float(np.median(finite)),
            "q2.5": float(np.percentile(finite, 2.5)),
            "q25": float(np.percentile(finite, 25.0)),
            "q75": float(np.percentile(finite, 75.0)),
            "q97.5": float(np.percentile(finite, 97.5)),
            "min": float(np.min(finite)),
            "max": float(np.max(finite)),
            "n_success": int(finite.size),
        })
    return pd.DataFrame(rows)


def _plot_parameter_distributions(path, samples, theta_names, max_params=30):
    import matplotlib  # noqa: PLC0415

    matplotlib.use("Agg")
    from matplotlib import pyplot as plt  # noqa: PLC0415

    samples = np.asarray(samples, dtype=np.float64)
    if samples.ndim != 2 or samples.shape[0] == 0:
        return

    n_show = min(int(max_params), samples.shape[1])
    ncols = min(4, n_show)
    nrows = int(np.ceil(n_show / ncols))

    fig, axes = plt.subplots(
        nrows,
        ncols,
        figsize=(4.2 * ncols, 3.0 * nrows),
        squeeze=False,
    )
    axes_flat = axes.ravel()

    for i in range(n_show):
        ax = axes_flat[i]
        vals = samples[:, i]
        vals = vals[np.isfinite(vals)]
        if vals.size:
            ax.hist(vals, bins=min(30, max(5, vals.size // 2)), alpha=0.85)
        ax.set_title(theta_names[i] if i < len(theta_names) else f"theta_{i}", fontsize=8)
        ax.grid(alpha=0.2)

    for ax in axes_flat[n_show:]:
        ax.set_visible(False)

    fig.suptitle("Bootstrap parameter distributions", fontsize=12, fontweight="bold")
    fig.tight_layout()
    fig.savefig(path, dpi=200)
    plt.close(fig)


def _save_prediction_intervals(
        *,
        outdir,
        problem,
        samples,
        theta_best,
        max_predictions=200,
):
    """Simulate bootstrap optima and save simple prediction interval arrays."""
    import pandas as pd  # noqa: PLC0415

    pred_dir = os.path.join(outdir, "bootstrap_prediction_intervals")
    os.makedirs(pred_dir, exist_ok=True)

    samples = np.asarray(samples, dtype=np.float64)
    if samples.ndim != 2 or samples.shape[0] == 0:
        return None

    if samples.shape[0] > max_predictions:
        idx = np.linspace(0, samples.shape[0] - 1, int(max_predictions), dtype=int)
        use_samples = samples[idx]
    else:
        use_samples = samples

    p_stack = []
    a_stack = []
    r_stack = []

    for theta in use_samples:
        try:
            sim = _simulate_full_for_uncertainty(problem, theta)
            P = _as_optional_array(sim.get("P_sim"))
            A = _as_optional_array(sim.get("A_sim"))
            R = _as_optional_array(sim.get("R_sim_rna", sim.get("R_sim")))
            if P is not None and np.all(np.isfinite(P)):
                p_stack.append(P)
            if A is not None and np.all(np.isfinite(A)):
                a_stack.append(A)
            if R is not None and np.all(np.isfinite(R)):
                r_stack.append(R)
        except Exception:
            continue

    def _write_interval(name, stack, t_values):
        if not stack:
            return None
        arr = np.stack(stack, axis=0)
        mean = np.mean(arr, axis=0)
        lo = np.percentile(arr, 2.5, axis=0)
        hi = np.percentile(arr, 97.5, axis=0)
        np.savez(
            os.path.join(pred_dir, f"{name}_intervals.npz"),
            mean=mean,
            lower=lo,
            upper=hi,
            samples_shape=np.array(arr.shape, dtype=np.int64),
        )

        rows = []
        for entity in range(mean.shape[0]):
            for ti in range(mean.shape[1]):
                rows.append({
                    "entity_index": entity,
                    "time_index": ti,
                    "time": float(t_values[ti]) if t_values is not None and ti < len(t_values) else ti,
                    "mean": float(mean[entity, ti]),
                    "q2.5": float(lo[entity, ti]),
                    "q97.5": float(hi[entity, ti]),
                })
        path = os.path.join(pred_dir, f"{name}_intervals.tsv")
        pd.DataFrame(rows).to_csv(path, sep="\t", index=False)
        return path

    t = np.asarray(getattr(problem, "t", []), dtype=np.float64)
    t_rna = np.asarray(getattr(problem, "t_rna", []), dtype=np.float64) if getattr(problem, "t_rna", None) is not None else None

    written = {
        "P_sim": _write_interval("P_sim", p_stack, t),
        "A_sim": _write_interval("A_sim", a_stack, t),
        "R_sim": _write_interval("R_sim", r_stack, t_rna),
    }
    return written


def run_residual_bootstrap_uncertainty(
        *,
        outdir: str,
        problem,
        theta_best: np.ndarray,
        posterior_cfg=None,
        theta_names: list[str] | None = None,
        w_phospho: float = 1.0,
        w_abundance: float = 1.0,
        w_reg: float = 1.0,
        w_mrna: float = 1.0,
) -> dict[str, Any]:
    """
    Residual-bootstrap parameter uncertainty by repeated optimizer refits.

    This replaces fragile MCMC for this ODE model. It samples synthetic datasets
    by resampling fitted residuals, then refits the original optimizer objective.
    """
    from phoscrosstalk.optimization import run_single_optimisation  # noqa: PLC0415

    unc_dir = os.path.join(outdir, "uncertainty")
    os.makedirs(unc_dir, exist_ok=True)

    theta_best = np.asarray(theta_best, dtype=np.float64)
    dim = theta_best.size
    if theta_names is None:
        theta_names = [f"theta_{i}" for i in range(dim)]

    n_bootstrap = int(_cfg_get(posterior_cfg, "n_bootstrap", _cfg_get(posterior_cfg, "num_bootstrap", 100)))
    seed = int(_cfg_get(posterior_cfg, "seed", 42))
    residual_mode = str(_cfg_get(posterior_cfg, "bootstrap_residual_mode", "case"))
    start_jitter = float(_cfg_get(posterior_cfg, "bootstrap_start_jitter", 0.0))
    max_steps = int(_cfg_get(posterior_cfg, "bootstrap_max_steps", _cfg_get(posterior_cfg, "max_steps", 200)))
    rtol = float(_cfg_get(posterior_cfg, "bootstrap_rtol", _cfg_get(posterior_cfg, "rtol", 1e-8)))
    atol = float(_cfg_get(posterior_cfg, "bootstrap_atol", _cfg_get(posterior_cfg, "atol", 1e-8)))
    ls_solver = str(_cfg_get(posterior_cfg, "ls_solver", "lm"))
    optx_adjoint = str(_cfg_get(posterior_cfg, "optx_adjoint", "checkpoint"))
    jac_mode = str(_cfg_get(posterior_cfg, "jac_mode", "bwd"))
    save_prediction_intervals = bool(_cfg_get(posterior_cfg, "save_prediction_intervals", True))
    max_prediction_samples = int(_cfg_get(posterior_cfg, "max_prediction_samples", 200))
    rebuild_s_prod_from_bootstrap = bool(_cfg_get(posterior_cfg, "rebuild_s_prod_from_bootstrap", True))

    rng = np.random.default_rng(seed)
    xl = np.asarray(problem.xl, dtype=np.float64)
    xu = np.asarray(problem.xu, dtype=np.float64)
    theta_best = _clip_theta_open(theta_best, xl, xu)

    logger.header("[*] Running residual-bootstrap uncertainty")
    logger.info(
        "[bootstrap] n=%d residual_mode=%s max_steps=%d start_jitter=%.3g",
        n_bootstrap,
        residual_mode,
        max_steps,
        start_jitter,
    )

    sim_best = _simulate_full_for_uncertainty(problem, theta_best)
    P_best = _as_optional_array(sim_best.get("P_sim"))
    A_best = _as_optional_array(sim_best.get("A_sim"))
    R_best = _as_optional_array(sim_best.get("R_sim_rna", sim_best.get("R_sim")))

    P_data = np.asarray(problem.P_data, dtype=np.float64)
    A_data = np.asarray(problem.A_scaled, dtype=np.float64)
    R_data = _as_optional_array(getattr(problem, "rna_obs_matched", None))

    if P_best is None or P_best.shape != P_data.shape:
        raise RuntimeError(
            f"[bootstrap] P simulation/data shape mismatch: "
            f"P_best={None if P_best is None else P_best.shape}, P_data={P_data.shape}"
        )

    resid_P = P_data - P_best

    resid_A = None
    if A_best is not None and A_data is not None and A_data.size > 0:
        # If A_sim is full K x T and A_data is observed subset, select observed rows.
        if A_best.shape != A_data.shape and getattr(problem, "prot_idx_for_A", None) is not None:
            try:
                A_best_for_loss = A_best[np.asarray(problem.prot_idx_for_A, dtype=int), :]
            except Exception:
                A_best_for_loss = A_best
        else:
            A_best_for_loss = A_best
        if A_best_for_loss.shape == A_data.shape:
            resid_A = A_data - A_best_for_loss

    resid_R = None
    if R_best is not None and R_data is not None and R_data.size > 0:
        if R_best.shape != R_data.shape and getattr(problem, "rna_model_prot_idx", None) is not None:
            try:
                R_best_for_loss = R_best[np.asarray(problem.rna_model_prot_idx, dtype=int), :]
            except Exception:
                R_best_for_loss = R_best
        else:
            R_best_for_loss = R_best
        if R_best_for_loss.shape == R_data.shape:
            resid_R = R_data - R_best_for_loss

    samples = []
    losses = []
    f_rows = []
    failures = []

    refit_kwargs = _base_refit_kwargs_from_problem(
        problem=problem,
        w_phospho=w_phospho,
        w_abundance=w_abundance,
        w_reg=w_reg,
        w_mrna=w_mrna,
    )

    if not _can_pickle(refit_kwargs):
        bad = _find_non_picklable_items(refit_kwargs)
        raise RuntimeError(
            "[bootstrap/runtime] refit kwargs are not picklable; cannot run "
            f"spawn-based parallel refits. Non-picklable keys: {bad}. "
            "Make sure problem has _k_act_rebuild_kwargs and _s_prod_rebuild_kwargs."
        )

    cpu_plan = _plan_uncertainty_runtime(
        problem,
        posterior_cfg,
        n_tasks=n_bootstrap,
        label="bootstrap",
    )

    tasks = []

    for b in range(n_bootstrap):
        P_boot = P_best + _resample_residual_matrix(rng, resid_P, mode=residual_mode)
        P_boot = np.nan_to_num(P_boot, nan=0.0, posinf=0.0, neginf=0.0)

        if resid_A is not None:
            A_boot = A_best_for_loss + _resample_residual_matrix(
                rng,
                resid_A,
                mode=residual_mode,
            )
            A_boot = np.nan_to_num(A_boot, nan=0.0, posinf=0.0, neginf=0.0)
        else:
            A_boot = A_data

        if resid_R is not None:
            R_boot = R_best_for_loss + _resample_residual_matrix(
                rng,
                resid_R,
                mode=residual_mode,
            )
            R_boot = np.nan_to_num(R_boot, nan=0.0, posinf=0.0, neginf=0.0)
        else:
            R_boot = R_data

        if start_jitter > 0:
            theta0 = theta_best + start_jitter * rng.normal(size=dim)
            theta0 = _clip_theta_open(theta0, xl, xu)
        else:
            theta0 = theta_best.copy()

        tasks.append(
            (
                b,
                theta0,
                refit_kwargs,
                P_boot,
                A_boot,
                R_boot,
                max_steps,
                rtol,
                atol,
                ls_solver,
                optx_adjoint,
                jac_mode,
                int(cpu_plan.threads_per_run),
                rebuild_s_prod_from_bootstrap,
            )
        )

    samples = []
    losses = []
    f_rows = []
    failures = []

    use_parallel = int(cpu_plan.n_parallel_runs) > 1

    if use_parallel:
        logger.info(
            "[bootstrap/runtime] Running %d bootstrap refits across %d workers "
            "with %d threads/worker.",
            len(tasks),
            int(cpu_plan.n_parallel_runs),
            int(cpu_plan.threads_per_run),
        )

        results_map = {}

        try:
            ctx = mp.get_context("spawn")
            with ProcessPoolExecutor(
                    max_workers=int(cpu_plan.n_parallel_runs),
                    mp_context=ctx,
            ) as pool:
                futures = {
                    pool.submit(_bootstrap_refit_worker, task): task[0]
                    for task in tasks
                }

                for future in as_completed(futures):
                    b = futures[future]
                    try:
                        result = future.result()
                    except Exception as exc:
                        result = (
                            b,
                            False,
                            None,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            f"{type(exc).__name__}: {exc}",
                        )
                    results_map[b] = result

            ordered_results = [results_map[i] for i in range(len(tasks))]

        except Exception as exc:
            logger.warning(
                "[bootstrap/runtime] ProcessPoolExecutor failed (%s); "
                "falling back to serial refits.",
                exc,
            )
            ordered_results = [_bootstrap_refit_worker(task) for task in tasks]

    else:
        logger.info("[bootstrap/runtime] Running bootstrap refits serially.")
        ordered_results = [_bootstrap_refit_worker(task) for task in tasks]

    for result in ordered_results:
        b, ok, theta_opt, total_loss, f1, f2, f3, f4, error = result

        if ok:
            theta_opt = _clip_theta_open(theta_opt, xl, xu)
            samples.append(theta_opt)
            losses.append(float(total_loss))
            f_rows.append([float(f1), float(f2), float(f3), float(f4)])
            logger.info(
                "[bootstrap] %04d/%04d success loss=%.4e",
                b + 1,
                n_bootstrap,
                float(total_loss),
            )
        else:
            failures.append(
                {
                    "bootstrap_index": int(b),
                    "error_type": error.split(":", 1)[0] if error else "Unknown",
                    "error": error,
                }
            )
            logger.warning(
                "[bootstrap] %04d/%04d failed: %s",
                b + 1,
                n_bootstrap,
                error,
            )

    import pandas as pd  # noqa: PLC0415

    samples_arr = np.asarray(samples, dtype=np.float64).reshape((-1, dim)) if samples else np.empty((0, dim))
    losses_arr = np.asarray(losses, dtype=np.float64)
    f_arr = np.asarray(f_rows, dtype=np.float64).reshape((-1, 4)) if f_rows else np.empty((0, 4))

    npz_path = os.path.join(unc_dir, "bootstrap_samples.npz")
    np.savez(
        npz_path,
        samples=samples_arr,
        losses=losses_arr,
        F=f_arr,
        theta_best=theta_best,
        theta_names=np.asarray(theta_names, dtype=str),
        n_requested=np.array(n_bootstrap, dtype=np.int64),
        n_success=np.array(samples_arr.shape[0], dtype=np.int64),
    )

    summary = _summarize_samples(samples_arr, theta_names)
    summary_path = os.path.join(unc_dir, "bootstrap_summary.tsv")
    summary.to_csv(summary_path, sep="\t", index=False)

    failures_df = pd.DataFrame(failures, columns=["bootstrap_index", "error_type", "error"])
    failures_path = os.path.join(unc_dir, "bootstrap_failures.tsv")
    failures_df.to_csv(failures_path, sep="\t", index=False)

    plot_path = os.path.join(unc_dir, "bootstrap_parameter_distributions.png")
    _plot_parameter_distributions(
        plot_path,
        samples_arr,
        theta_names,
        max_params=int(_cfg_get(posterior_cfg, "plot_params", 30)),
    )

    pred_written = None
    if save_prediction_intervals and samples_arr.shape[0] > 0:
        pred_written = _save_prediction_intervals(
            outdir=unc_dir,
            problem=problem,
            samples=samples_arr,
            theta_best=theta_best,
            max_predictions=max_prediction_samples,
        )

    meta = {
        "method": "residual_bootstrap",
        "n_requested": int(n_bootstrap),
        "n_success": int(samples_arr.shape[0]),
        "n_failed": int(len(failures)),
        "residual_mode": residual_mode,
        "max_steps": int(max_steps),
        "rtol": float(rtol),
        "atol": float(atol),
        "ls_solver": ls_solver,
        "optx_adjoint": optx_adjoint,
        "jac_mode": jac_mode,
        "start_jitter": float(start_jitter),
        "rebuild_s_prod_from_bootstrap": bool(rebuild_s_prod_from_bootstrap),
    }
    meta_path = os.path.join(unc_dir, "bootstrap_metadata.json")
    with open(meta_path, "w", encoding="utf-8") as fh:
        json.dump(meta, fh, indent=2)

    logger.success(
        "[bootstrap] complete: success=%d failed=%d output=%s",
        int(samples_arr.shape[0]),
        int(len(failures)),
        unc_dir,
    )

    return {
        "samples": samples_arr,
        "losses": losses_arr,
        "F": f_arr,
        "summary": summary,
        "failures": failures_df,
        "outdir": unc_dir,
        "prediction_intervals": pred_written,
        "metadata": meta,
    }


def _plot_profile_likelihood(profile_df, outdir, theta_names):
    import matplotlib  # noqa: PLC0415

    matplotlib.use("Agg")
    from matplotlib import pyplot as plt  # noqa: PLC0415

    if profile_df.empty:
        return None

    prof_dir = os.path.join(outdir, "profile_likelihood")
    os.makedirs(prof_dir, exist_ok=True)

    for param_idx, sub in profile_df.groupby("parameter_index"):
        sub = sub.sort_values("fixed_value")
        name = theta_names[int(param_idx)] if int(param_idx) < len(theta_names) else f"theta_{param_idx}"

        fig, ax = plt.subplots(figsize=(6.5, 4.2))
        ok = sub["success"].astype(bool).values
        if np.any(ok):
            ax.plot(
                sub.loc[ok, "fixed_value"],
                sub.loc[ok, "total_loss"],
                marker="o",
                lw=1.8,
                label="profile loss",
            )
        if np.any(~ok):
            ax.scatter(
                sub.loc[~ok, "fixed_value"],
                np.full(np.sum(~ok), np.nanmax(sub["total_loss"].values[ok]) if np.any(ok) else 0.0),
                marker="x",
                label="failed",
            )
        ax.set_title(f"Profile likelihood: {name}", fontsize=11, fontweight="bold")
        ax.set_xlabel("fixed parameter value")
        ax.set_ylabel("profiled total loss")
        ax.grid(alpha=0.25)
        ax.legend(fontsize=8)
        fig.tight_layout()
        fig.savefig(os.path.join(prof_dir, f"profile_param_{int(param_idx):04d}.png"), dpi=200)
        plt.close(fig)

    return prof_dir

def _profile_refit_worker(task):
    """
    Process worker for one profile-likelihood grid point.
    """
    (
        task_index,
        param_idx,
        grid_index,
        fixed_value,
        theta0,
        refit_kwargs,
        fix_lambda,
        max_steps,
        rtol,
        atol,
        ls_solver,
        optx_adjoint,
        jac_mode,
        threads_per_worker,
        theta_name,
    ) = task

    from phoscrosstalk import runtime_env  # noqa: PLC0415

    runtime_env.apply_cpu_env(int(threads_per_worker), overwrite=True)

    try:
        import jax.numpy as jnp  # noqa: PLC0415
        from phoscrosstalk.optimization import run_single_optimisation  # noqa: PLC0415

        base_residuals_fn = _residuals_fn_from_refit_kwargs(dict(refit_kwargs))
        sqrt_lambda = np.sqrt(float(fix_lambda))

        def prof_residuals_fn(theta, args):
            residuals, aux = base_residuals_fn(theta, args)
            fix_resid = jnp.asarray(
                [sqrt_lambda * (theta[int(param_idx)] - float(fixed_value))],
                dtype=jnp.float64,
            )
            return jnp.concatenate([residuals, fix_resid]), aux

        theta_opt, total_loss, f1, f2, f3, f4 = run_single_optimisation(
            prof_residuals_fn,
            np.asarray(theta0, dtype=np.float64),
            max_steps=int(max_steps),
            rtol=float(rtol),
            atol=float(atol),
            verbose=False,
            ls_solver=str(ls_solver),
            optx_adjoint=str(optx_adjoint),
            jac_mode=str(jac_mode),
        )

        return {
            "task_index": int(task_index),
            "parameter_index": int(param_idx),
            "parameter": str(theta_name),
            "grid_index": int(grid_index),
            "fixed_value": float(fixed_value),
            "optimized_value": float(theta_opt[int(param_idx)]),
            "total_loss": float(total_loss),
            "f1": float(f1),
            "f2": float(f2),
            "f3": float(f3),
            "f4": float(f4),
            "success": True,
            "error": "",
            "theta_opt": np.asarray(theta_opt, dtype=np.float64),
        }

    except Exception as exc:
        return {
            "task_index": int(task_index),
            "parameter_index": int(param_idx),
            "parameter": str(theta_name),
            "grid_index": int(grid_index),
            "fixed_value": float(fixed_value),
            "optimized_value": np.nan,
            "total_loss": np.nan,
            "f1": np.nan,
            "f2": np.nan,
            "f3": np.nan,
            "f4": np.nan,
            "success": False,
            "error": f"{type(exc).__name__}: {exc}",
            "theta_opt": None,
        }

def run_profile_likelihood_uncertainty(
        *,
        outdir: str,
        problem,
        theta_best: np.ndarray,
        posterior_cfg=None,
        theta_names: list[str] | None = None,
        parameter_indices: list[int] | None = None,
        w_phospho: float = 1.0,
        w_abundance: float = 1.0,
        w_reg: float = 1.0,
        w_mrna: float = 1.0,
) -> dict[str, Any]:
    """
    Profile-likelihood style identifiability analysis.

    Each selected parameter is fixed over a grid by adding a very strong
    equality residual, while all parameters are re-optimized. This is a robust
    optimizer-compatible approximation to constrained profiling without needing
    a new reduced-dimension optimizer.
    """
    from phoscrosstalk.optimization import run_single_optimisation  # noqa: PLC0415
    import pandas as pd  # noqa: PLC0415
    import jax.numpy as jnp  # noqa: PLC0415

    unc_dir = os.path.join(outdir, "uncertainty")
    prof_dir = os.path.join(unc_dir, "profile_likelihood")
    os.makedirs(prof_dir, exist_ok=True)

    theta_best = np.asarray(theta_best, dtype=np.float64)
    dim = theta_best.size
    if theta_names is None:
        theta_names = [f"theta_{i}" for i in range(dim)]

    xl = np.asarray(problem.xl, dtype=np.float64)
    xu = np.asarray(problem.xu, dtype=np.float64)
    theta_best = _clip_theta_open(theta_best, xl, xu)

    if parameter_indices is None:
        profile_params = int(_cfg_get(posterior_cfg, "profile_params", min(12, dim)))
        parameter_indices = list(range(min(profile_params, dim)))
    parameter_indices = [int(i) for i in parameter_indices if 0 <= int(i) < dim]

    n_points = int(_cfg_get(posterior_cfg, "profile_points", 21))
    grid_fraction = float(_cfg_get(posterior_cfg, "profile_grid_fraction", 1.0))
    fix_lambda = float(_cfg_get(posterior_cfg, "profile_fix_lambda", 1e8))
    max_steps = int(_cfg_get(posterior_cfg, "profile_max_steps", _cfg_get(posterior_cfg, "max_steps", 300)))
    rtol = float(_cfg_get(posterior_cfg, "profile_rtol", _cfg_get(posterior_cfg, "rtol", 1e-8)))
    atol = float(_cfg_get(posterior_cfg, "profile_atol", _cfg_get(posterior_cfg, "atol", 1e-8)))
    ls_solver = str(_cfg_get(posterior_cfg, "ls_solver", "lm"))
    optx_adjoint = str(_cfg_get(posterior_cfg, "optx_adjoint", "implicit"))
    jac_mode = str(_cfg_get(posterior_cfg, "jac_mode", "fwd"))

    logger.header("[*] Running profile-likelihood uncertainty")
    logger.info(
        "[profile] params=%s points=%d max_steps=%d fix_lambda=%.3e",
        parameter_indices,
        n_points,
        max_steps,
        fix_lambda,
    )

    base_residuals_fn = _make_refit_residuals_fn(
        problem=problem,
        P_data=problem.P_data,
        A_scaled=problem.A_scaled,
        rna_data_scaled=getattr(problem, "rna_obs_matched", None),
        w_phospho=w_phospho,
        w_abundance=w_abundance,
        w_reg=w_reg,
        w_mrna=w_mrna,
        rebuild_s_prod_from_P=False,
    )

    rows = []
    profiled_thetas = []
    profile_sqrt_lambda = np.sqrt(fix_lambda)

    for param_idx in parameter_indices:
        center = float(theta_best[param_idx])
        lo = float(xl[param_idx])
        hi = float(xu[param_idx])
        if grid_fraction < 1.0:
            half = 0.5 * grid_fraction * (hi - lo)
            lo_g = max(lo, center - half)
            hi_g = min(hi, center + half)
        else:
            lo_g, hi_g = lo, hi

        eps = max(1e-10 * (hi - lo), 1e-12)
        grid = np.linspace(lo_g + eps, hi_g - eps, n_points)

        logger.info(
            "[profile] parameter=%d %s grid=[%.4e, %.4e] points=%d",
            param_idx,
            theta_names[param_idx] if param_idx < len(theta_names) else f"theta_{param_idx}",
            float(grid[0]),
            float(grid[-1]),
            int(len(grid)),
        )

        refit_kwargs = _base_refit_kwargs_from_problem(
            problem=problem,
            w_phospho=w_phospho,
            w_abundance=w_abundance,
            w_reg=w_reg,
            w_mrna=w_mrna,
        )

        refit_kwargs["P_data"] = np.asarray(problem.P_data, dtype=np.float64)
        refit_kwargs["A_scaled"] = np.asarray(problem.A_scaled, dtype=np.float64)
        refit_kwargs["rna_data_scaled"] = _as_optional_array(
            getattr(problem, "rna_obs_matched", None)
        )

        if not _can_pickle(refit_kwargs):
            bad = _find_non_picklable_items(refit_kwargs)
            raise RuntimeError(
                "[profile/runtime] refit kwargs are not picklable; cannot run "
                f"spawn-based parallel profile refits. Non-picklable keys: {bad}. "
                "Make sure problem has _k_act_rebuild_kwargs and _s_prod_rebuild_kwargs."
            )

        tasks = []
        task_index = 0

        for param_idx in parameter_indices:
            center = float(theta_best[param_idx])
            lo = float(xl[param_idx])
            hi = float(xu[param_idx])

            if grid_fraction < 1.0:
                half = 0.5 * grid_fraction * (hi - lo)
                lo_g = max(lo, center - half)
                hi_g = min(hi, center + half)
            else:
                lo_g, hi_g = lo, hi

            eps = max(1e-10 * (hi - lo), 1e-12)
            grid = np.linspace(lo_g + eps, hi_g - eps, n_points)

            for gi, fixed_value in enumerate(grid):
                theta0 = theta_best.copy()
                theta0[param_idx] = fixed_value
                theta0 = _clip_theta_open(theta0, xl, xu)

                theta_name = (
                    theta_names[param_idx]
                    if param_idx < len(theta_names)
                    else f"theta_{param_idx}"
                )

                tasks.append(
                    (
                        task_index,
                        int(param_idx),
                        int(gi),
                        float(fixed_value),
                        theta0,
                        refit_kwargs,
                        float(fix_lambda),
                        int(max_steps),
                        float(rtol),
                        float(atol),
                        str(ls_solver),
                        str(optx_adjoint),
                        str(jac_mode),
                        None,  # filled after runtime plan
                        theta_name,
                    )
                )
                task_index += 1

        cpu_plan = _plan_uncertainty_runtime(
            problem,
            posterior_cfg,
            n_tasks=len(tasks),
            label="profile",
        )

        tasks = [
            (*task[:-2], int(cpu_plan.threads_per_run), task[-1])
            for task in tasks
        ]

        use_parallel = int(cpu_plan.n_parallel_runs) > 1

        if use_parallel:
            logger.info(
                "[profile/runtime] Running %d profile refits across %d workers "
                "with %d threads/worker.",
                len(tasks),
                int(cpu_plan.n_parallel_runs),
                int(cpu_plan.threads_per_run),
            )

            results_map = {}

            try:
                ctx = mp.get_context("spawn")
                with ProcessPoolExecutor(
                        max_workers=int(cpu_plan.n_parallel_runs),
                        mp_context=ctx,
                ) as pool:
                    futures = {
                        pool.submit(_profile_refit_worker, task): task[0]
                        for task in tasks
                    }

                    for future in as_completed(futures):
                        ti = futures[future]
                        try:
                            result = future.result()
                        except Exception as exc:
                            result = {
                                "task_index": int(ti),
                                "parameter_index": -1,
                                "parameter": "",
                                "grid_index": -1,
                                "fixed_value": np.nan,
                                "optimized_value": np.nan,
                                "total_loss": np.nan,
                                "f1": np.nan,
                                "f2": np.nan,
                                "f3": np.nan,
                                "f4": np.nan,
                                "success": False,
                                "error": f"{type(exc).__name__}: {exc}",
                                "theta_opt": None,
                            }

                        results_map[int(result["task_index"])] = result

                ordered_results = [results_map[i] for i in range(len(tasks))]

            except Exception as exc:
                logger.warning(
                    "[profile/runtime] ProcessPoolExecutor failed (%s); "
                    "falling back to serial profile refits.",
                    exc,
                )
                ordered_results = [_profile_refit_worker(task) for task in tasks]

        else:
            logger.info("[profile/runtime] Running profile refits serially.")
            ordered_results = [_profile_refit_worker(task) for task in tasks]

        rows = []
        profiled_thetas = []

        for result in ordered_results:
            theta_opt = result.pop("theta_opt", None)

            if theta_opt is not None:
                theta_opt = _clip_theta_open(theta_opt, xl, xu)
                profiled_thetas.append(theta_opt)

            rows.append(result)

    profile_df = pd.DataFrame(rows)
    profile_path = os.path.join(prof_dir, "profile_likelihood.tsv")
    profile_df.to_csv(profile_path, sep="\t", index=False)

    profiled_arr = np.asarray(profiled_thetas, dtype=np.float64).reshape((-1, dim)) if profiled_thetas else np.empty((0, dim))
    np.savez(
        os.path.join(prof_dir, "profile_thetas.npz"),
        theta=profiled_arr,
        theta_best=theta_best,
        theta_names=np.asarray(theta_names, dtype=str),
    )

    plot_dir = _plot_profile_likelihood(profile_df, unc_dir, theta_names)

    meta = {
        "method": "profile_likelihood",
        "parameter_indices": parameter_indices,
        "profile_points": int(n_points),
        "profile_grid_fraction": float(grid_fraction),
        "profile_fix_lambda": float(fix_lambda),
        "max_steps": int(max_steps),
        "rtol": float(rtol),
        "atol": float(atol),
        "ls_solver": ls_solver,
        "optx_adjoint": optx_adjoint,
        "jac_mode": jac_mode,
    }
    with open(os.path.join(prof_dir, "profile_metadata.json"), "w", encoding="utf-8") as fh:
        json.dump(meta, fh, indent=2)

    logger.success("[profile] complete: %s", prof_dir)

    return {
        "profile": profile_df,
        "theta": profiled_arr,
        "outdir": prof_dir,
        "plot_dir": plot_dir,
        "metadata": meta,
    }


def run_optimizer_uncertainty(
        *,
        outdir: str,
        problem,
        theta_best: np.ndarray,
        posterior_cfg=None,
        theta_names: list[str] | None = None,
        w_phospho: float = 1.0,
        w_abundance: float = 1.0,
        w_reg: float = 1.0,
        w_mrna: float = 1.0,
) -> dict[str, Any]:
    """
    Unified uncertainty runner controlled by posterior_cfg.method.

    Supported methods:
        - 'bootstrap'
        - 'profile'
        - 'both'
        - 'bootstrap_profile'
    """
    method = str(_cfg_get(posterior_cfg, "method", "bootstrap")).lower()
    results: dict[str, Any] = {}

    if method in {"bootstrap", "both", "bootstrap_profile", "residual_bootstrap"}:
        results["bootstrap"] = run_residual_bootstrap_uncertainty(
            outdir=outdir,
            problem=problem,
            theta_best=theta_best,
            posterior_cfg=posterior_cfg,
            theta_names=theta_names,
            w_phospho=w_phospho,
            w_abundance=w_abundance,
            w_reg=w_reg,
            w_mrna=w_mrna,
        )

    if method in {"profile", "both", "bootstrap_profile", "profile_likelihood"}:
        results["profile"] = run_profile_likelihood_uncertainty(
            outdir=outdir,
            problem=problem,
            theta_best=theta_best,
            posterior_cfg=posterior_cfg,
            theta_names=theta_names,
            w_phospho=w_phospho,
            w_abundance=w_abundance,
            w_reg=w_reg,
            w_mrna=w_mrna,
        )

    if not results:
        raise ValueError(
            f"[uncertainty] Unknown posterior/uncertainty method={method!r}. "
            "Use 'bootstrap', 'profile', or 'both'."
        )

    return results