#!/usr/bin/env python3
"""
Inspects a fitted_params.npz file generated by fit_pymoo.py.
Displays parameters in readable tables with their corresponding Protein/Site/Kinase labels.
"""

import numpy as np
import argparse
import pandas as pd
import sys

def main():
    parser = argparse.ArgumentParser(description="Inspect fitted parameters from NPZ")
    parser.add_argument("--npz", default="../network_fit/fitted_params.npz", help="Path to the NPZ file")
    args = parser.parse_args()

    try:
        data = np.load(args.npz, allow_pickle=True)
    except FileNotFoundError:
        print(f"[!] Error: File {args.npz} not found.")
        sys.exit(1)

    keys = list(data.keys())
    print(f"[*] Loaded {args.npz}")
    print(f"[*] Available keys: {keys}\n")

    # --- Check if we have the enriched format with labels ---
    has_labels = 'proteins' in keys and 'sites' in keys and 'kinases' in keys

    if not has_labels:
        print("[!] Warning: NPZ file does not contain metadata ('proteins', 'sites', etc.).")
        print("    Running fallback raw inspection...\n")
        for key in keys:
            val = data[key]
            if isinstance(val, np.ndarray) and val.size > 20:
                print(f"{key}: shape={val.shape} (stats: min={val.min():.3f}, max={val.max():.3f})")
            else:
                print(f"{key}: {val}")
        return

    # --- Load Metadata ---
    proteins = data['proteins']
    sites = data['sites']
    kinases = data['kinases']

    print(f"[*] Model Dimensions:")
    print(f"    Proteins: {len(proteins)}")
    print(f"    Sites:    {len(sites)}")
    print(f"    Kinases:  {len(kinases)}\n")

    # --- Helper to print dataframe ---
    def print_table(title, df):
        print(f"=== {title} ===")
        print(df.to_string(index=False))
        print("-" * 40 + "\n")

    # 1. Protein-specific Parameters
    # k_act, k_deact, s_prod, d_deg
    if 'k_act' in keys:
        df_prot = pd.DataFrame({
            'Protein': proteins,
            'k_act (Activation)': data['k_act'],
            'k_deact (Deactivation)': data['k_deact'],
            's_prod (Synthesis)': data['s_prod'],
            'd_deg (Degradation)': data['d_deg']
        })
        print_table("Protein Dynamics", df_prot)

    # 2. Kinase-specific Parameters
    # alpha, kK_act, kK_deact
    if 'alpha' in keys:
        df_kin = pd.DataFrame({
            'Kinase': kinases,
            'Alpha (Global Str)': data['alpha'],
            'kK_act (Kinase Act)': data['kK_act'],
            'kK_deact (Kinase Deact)': data['kK_deact']
        })
        print_table("Kinase Parameters", df_kin)

    # 3. Site-specific Parameters
    # k_off
    if 'k_off' in keys:
        df_site = pd.DataFrame({
            'Site': sites,
            'k_off (Phosphatase Rate)': data['k_off']
        })
        print_table("Site Dephosphorylation Rates", df_site)

    # 4. Global Scalars
    print("=== Global Coupling Parameters ===")
    if 'beta_g' in keys:
        print(f"  beta_g (Global Coupling): {data['beta_g']:.5f}")
    if 'beta_l' in keys:
        print(f"  beta_l (Local Coupling):  {data['beta_l']:.5f}")
    print("-" * 40 + "\n")

if __name__ == "__main__":
    main()