from phoscrosstalk.utils.gitsync import sync_gitignore
from phoscrosstalk.utils.showconfig import _save_model_entities_table
from phoscrosstalk.utils.showconfig import _print_config_summary

print_config_summary = _print_config_summary
save_model_table = _save_model_entities_table